<div class="panel panel-default">
    <div class="panel-body">

        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Username</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td>Istran</td>
                <td>Net</td>
                <td>@istran</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Billy</td>
                <td>Joe</td>
                <td>@Bjoe</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Elvis</td>
                <td>Preley</td>
                <td>@elvisp</td>
            </tr>
            </tbody>
        </table>


    </div>
</div>