<!DOCTYPE html>
<html>
<head>
    <title>MYX Dashboard</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- bootstrap -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet"/>

    <!-- theme -->
    <link rel="stylesheet" type="text/css" href="/assets/css/theme/default.css"/>

    <!-- libraries -->
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/css/elements/signin.css"/>


    <!-- open sans font -->
    <link
        href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
        rel='stylesheet' type='text/css'/>

    <!--[if lt IE 9]>
    <script src="/assets/js/html5.js"></script>
    <![endif]-->

</head>
<body class="onepage">
<div class="navbar navbar-default navbar-fixed-top">
    <a class="navbar-brand" href="/"><b>LINE</b>BUILD</a>
</div>
<br><br>
<?php echo $this->layout()->content;?>


<!-- scripts -->
<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/bootstrap.js"></script>
<script src="/assets/js/theme.js"></script>


</body>
</html>