<div class="row">
    <div class="col-md-6">
        <form class="form-horizontal" method="get" data-validate="parsley">


            <div class="form-group">
                <label class="col-lg-3 control-label">Email</label>

                <div class="col-lg-8">
                    <input type="text" name="email" placeholder="test@example.com"
                           class="bg-focus form-control parsley-validated" data-required="true" data-type="email">
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Password</label>

                <div class="col-lg-8">
                    <input type="password" name="password" placeholder="Password" class="bg-focus form-control">
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Username</label>

                <div class="col-lg-8">
                    <input type="text" name="username" placeholder="Username" data-required="true"
                           class="form-control parsley-validated">
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Role account</label>

                <div class="col-lg-4">
                    <select name="account" class="form-control">
                        <option value="1">Editor</option>
                        <option value="0">Admin</option>
                    </select>
                </div>
            </div>





            <div class="form-group">
                <div class="col-lg-9 pull-right">
                    <a href="<?php echo $this->url('user');?>" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-info">Save changes</button>
                </div>
            </div>
        </form>
    </div>

</div>